### ISSUE TITLE
t_net.alpha_noise

### ISSUE THREAD

**Issue by wtj-zhong** [2j1ejyu/SF-NeRF#1]
wonderful job
But when I run your code I encounter a problem KeyError: 't_net.alpha_noise' I want to know the reason of this problem? Is this parameter defined by myself?
Here is my error:
python train.py\
--dataset_name phototourism \
--config ./configs/phototourism.yaml
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/home/wtj/anaconda3/envs/sfnerf/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
   warnings. warn(
/home/wtj/anaconda3/envs/sfnerf/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
   warnings. warn(msg)
Loading model from: /home/wtj/anaconda3/envs/sfnerf/lib/python3.9/site-packages/lpips/weights/v0.1/alex.pth
Traceback (most recent call last):
   File "/home/wtj/desktop/nerfw/SF-NeRF/train.py", line 69, in <module>
     main(parse_args(parser))
   File "/home/wtj/desktop/nerfw/SF-NeRF/train.py", line 33, in main
     system = NeRFSystem(hparams)
   File "/home/wtj/desktop/nerfw/SF-NeRF/models/nerf_system.py", line 73, in __init__
     alpha_noise=hparams['t_net.alpha_noise'],
KeyError: 't_net.alpha_noise'

**Comment by 2j1ejyu** [comment]
Thank you for your interest. It seems that the code is not the latest version. The parameter "t_net.alpha_noise" is not used in the latest version, thus it should be erased.
I apologize for the confusion and I'll update the code later as soon as possible.

-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2023. 6. 23. (금) 23:15 (GMT+09:00)
Subject: [2j1ejyu/SF-NeRF] t_net.alpha_noise (Issue #1)
 
wonderful job
But when I run your code I encounter a problem KeyError: 't_net.alpha_noise' I want to know the reason of this problem? Is this parameter defined by myself?
Here is my error:
python train.py
--dataset_name phototourism
--config ./configs/phototourism.yaml
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/home/wtj/anaconda3/envs/sfnerf/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
warnings. warn(
/home/wtj/anaconda3/envs/sfnerf/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or None for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing weights=AlexNet_Weights.IMAGENET1K_V1. You can also use weights=AlexNet_Weights.DEFAULT to get the most up-to-date weights.
warnings. warn(msg)
Loading model from: /home/wtj/anaconda3/envs/sfnerf/lib/python3.9/site-packages/lpips/weights/v0.1/alex.pth
Traceback (most recent call last):
File "/home/wtj/desktop/nerfw/SF-NeRF/train.py", line 69, in
main(parse_args(parser))
File "/home/wtj/desktop/nerfw/SF-NeRF/train.py", line 33, in main
system = NeRFSystem(hparams)
File "/home/wtj/desktop/nerfw/SF-NeRF/models/nerf_system.py", line 73, in init
alpha_noise=hparams['t_net.alpha_noise'],
KeyError: 't_net.alpha_noise'

**Comment by wtj-zhong** [comment]
Thank you for your work. Wishing you academic progress and a happy mood

**Comment by 3D-A** [comment]
Thank you for your wonderful job! could you share the pretrained checkpoint? Thank you very much
